In [1]:
import os
import pandas as pd

In [5]:
import os

DATA_FOLDER = "."

dat_files = []

for root, folders, files in os.walk(DATA_FOLDER):
    for file in files:
        if file.lower().endswith(".dat"):
            dat_files.append(os.path.join(root, file))

print("Number of DAT files:", len(dat_files))

Number of DAT files: 371

In [6]:
print(dat_files[0])

./157_SALES_DATA_NNME_17082026.DAT

In [7]:
with open(dat_files[0], "r", encoding="latin1", errors="replace") as file:
    for line in file:
        if line.startswith("B;"):
            print(line)
            break

B;157;6054891;1;20260817 01:04;;;18;CASUARINA CRES;CRESCENT HEAD;2440;744.6;M;20230505;20260811;799000;R1;V;VACANT LAND;;ACH;;;AW365481;

In [8]:
fields = line.rstrip("\n\r").split(";")

for i, value in enumerate(fields):
    print(i, "=", value)

0 = B
1 = 157
2 = 6054891
3 = 1
4 = 20260817 01:04
5 =
6 =
7 = 18
8 = CASUARINA CRES
9 = CRESCENT HEAD
10 = 2440
11 = 744.6
12 = M
13 = 20230505
14 = 20260811
15 = 799000
16 = R1
17 = V
18 = VACANT LAND
19 =
20 = ACH
21 =
22 =
23 = AW365481
24 =

In [9]:
for filepath in dat_files:

    with open(filepath, "r", encoding="latin1", errors="replace") as file:

        for line in file:

            if not line.startswith("B;"):
                continue

            fields = line.rstrip("\n\r").split(";")

            if len(fields) > 18:
                suburb = fields[9].strip().upper()

                if suburb == "CHATSWOOD":
                    print(line)
                    break

        else:
            continue

        break

B;092;960871;4;20260810 01:03;;;11;HERCULES ST;CHATSWOOD;2067;1067.35;M;20260606;20260803;4600000;R2;R;RESIDENCE;;RAC;;;AW345678;

In [10]:
fields = line.rstrip("\n\r").split(";")

for i, value in enumerate(fields):
    print(i, "=", value)

0 = B
1 = 092
2 = 960871
3 = 4
4 = 20260810 01:03
5 =
6 =
7 = 11
8 = HERCULES ST
9 = CHATSWOOD
10 = 2067
11 = 1067.35
12 = M
13 = 20260606
14 = 20260803
15 = 4600000
16 = R2
17 = R
18 = RESIDENCE
19 =
20 = RAC
21 =
22 =
23 = AW345678
24 =

In [14]:
target_suburbs = {
    "CHATSWOOD",
    "PARRAMATTA",
    "BLACKTOWN"
}

records = []

for filepath in dat_files:

    with open(filepath, "r", encoding="latin1", errors="replace") as file:

        for line in file:

            if not line.startswith("B;"):
                continue

            fields = line.rstrip("\n\r").split(";")

            if len(fields) < 24:
                continue

            suburb = fields[9].strip().upper()

            if suburb not in target_suburbs:
                continue

            records.append({
                "Property_ID_Raw": fields[2].strip(),
                "Sale_Counter": fields[3].strip(),
                "Street_Number": fields[7].strip(),
                "Street_Name": fields[8].strip(),
                "Suburb": suburb.title(),
                "Postcode": fields[10].strip(),
                "Land Size": fields[11].strip(),
                "Contract_Date": fields[13].strip(),
                "Settlement_Date": fields[14].strip(),
                "Sale_Price": fields[15].strip(),
                "Zoning": fields[16].strip(),
                "Property_type": fields[18].strip(),
                "Dealing_Number": fields[23].strip()
            })

df = pd.DataFrame(records)

print("Total extracted records:", len(df))
df.head(10)

Total extracted records: 132

,Property_ID_Raw,Sale_Counter,Street_Number,Street_Name,Suburb,Postcode,Land Size,Contract_Date,Settlement_Date,Sale_Price,Zoning,Property_type,Dealing_Number
0,3410896,2,31,THIRD AVE,Blacktown,2148,,20260705,20260817,420000,,RESIDENCE,AW379402
1,4166943,7,3,BALMORAL ST,Blacktown,2148,104,20260705,20260814,600000,,RESIDENCE,AW377022
2,6069557,16,105,SUNNYHOLT RD,Blacktown,2148,506.5,20260603,20260618,2079000,R4,VACANT LAND,AW221121
3,6069558,17,107,SUNNYHOLT RD,Blacktown,2148,336.9,20260603,20260618,2079000,R4,VACANT LAND,AW221121
4,6069560,18,109,SUNNYHOLT RD,Blacktown,2148,336.3,20260603,20260618,2079000,R4,VACANT LAND,AW221121
5,6069561,19,111,SUNNYHOLT RD,Blacktown,2148,335.6,20260603,20260618,2079000,R4,VACANT LAND,AW221121
6,6066721,25,9,HIGHLANDS CRES,Blacktown,2148,238,20250329,20260820,950000,,RESIDENCE,AW391124
7,6044673,30,99,STEPHEN ST,Blacktown,2148,512,20251107,20260401,1495000,R2,RESIDENCE,AV999718
8,2166863,85,28,CAVENDISH AVE,Blacktown,2148,556.4,20260706,20260817,1110000,R2,RESIDENCE,AW379383
9,2159777,90,27,BIMBIL ST,Blacktown,2148,689.2,20260705,20260817,1310000,R2,RESIDENCE,AW381289

In [15]:
df["Suburb"].value_counts()

Suburb
Blacktown     50
Chatswood     41
Parramatta    41
Name: count, dtype: int64

In [16]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
Property_ID_Raw    0
Sale_Counter       0
Street_Number      0
Street_Name        0
Suburb             0
Postcode           0
Land Size          0
Contract_Date      0
Settlement_Date    0
Sale_Price         0
Zoning             0
Property_type      0
Dealing_Number     0
dtype: int64

In [17]:
print(df.dtypes)

Property_ID_Raw    object
Sale_Counter       object
Street_Number      object
Street_Name        object
Suburb             object
Postcode           object
Land Size          object
Contract_Date      object
Settlement_Date    object
Sale_Price         object
Zoning             object
Property_type      object
Dealing_Number     object
dtype: object

In [18]:
print(df["Zoning"].value_counts(dropna=False))

Zoning
      95
R2    29
R4     4
E4     2
R1     1
C4     1
Name: count, dtype: int64

In [19]:
# Convert numeric columns
df["Sale_Price"] = pd.to_numeric(
    df["Sale_Price"],
    errors="coerce"
)

df["Land Size"] = pd.to_numeric(
    df["Land Size"],
    errors="coerce"
)

df["Postcode"] = pd.to_numeric(
    df["Postcode"],
    errors="coerce"
)

# Convert dates
df["Contract_Date"] = pd.to_datetime(
    df["Contract_Date"],
    format="%Y%m%d",
    errors="coerce"
)

df["Settlement_Date"] = pd.to_datetime(
    df["Settlement_Date"],
    format="%Y%m%d",
    errors="coerce"
)

print(df.dtypes)

Property_ID_Raw            object
Sale_Counter               object
Street_Number              object
Street_Name                object
Suburb                     object
Postcode                    int64
Land Size                 float64
Contract_Date      datetime64[ns]
Settlement_Date    datetime64[ns]
Sale_Price                  int64
Zoning                     object
Property_type              object
Dealing_Number             object
dtype: object

In [20]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

missing

                 Missing_Count  Missing_Percentage
Property_ID_Raw              0                0.00
Sale_Counter                 0                0.00
Street_Number                0                0.00
Street_Name                  0                0.00
Suburb                       0                0.00
Postcode                     0                0.00
Land Size                   57               43.18
Contract_Date                0                0.00
Settlement_Date              0                0.00
Sale_Price                   0                0.00
Zoning                       0                0.00
Property_type                0                0.00
Dealing_Number               0                0.00

In [22]:
print("Minimum price:", df["Sale_Price"].min())
print("Maximum price:", df["Sale_Price"].max())
print("Median price:", df["Sale_Price"].median())
print("Mean price:", df["Sale_Price"].mean())
df.groupby("Suburb")["Sale_Price"].agg(
    ["count", "min", "median", "mean", "max"]
)

Minimum price: 312000
Maximum price: 7400000
Median price: 865000.0
Mean price: 1295269.0151515151

            count     min     median          mean      max
Suburb
Blacktown      50  410000   958500.0  9.677800e+05  2079000
Chatswood      41  565400  2325000.0  2.366059e+06  7400000
Parramatta     41  312000   600000.0  6.238564e+05  1300000

In [23]:
df["Property_type"].value_counts(dropna=False)

Property_type
RESIDENCE      122
COMMERCIAL       5
VACANT LAND      4
OFFICE           1
Name: count, dtype: int64

In [27]:
pd.crosstab(
    df["Suburb"],
    df["Property_type"]
)

Property_type  COMMERCIAL  OFFICE  RESIDENCE  VACANT LAND
Suburb
Blacktown               1       0         45            4
Chatswood               3       1         37            0
Parramatta              1       0         40            0

In [26]:
df.groupby("Suburb")["Land Size"].agg(
    ["count", "min", "median", "mean", "max"]
)

            count    min  median        mean     max
Suburb
Blacktown      34  101.0   547.8  462.102647   866.3
Chatswood      27  105.0   178.0  410.066667  1416.0
Parramatta     14   65.0   104.5  105.928571   192.0

In [28]:
df.nlargest(5, "Sale_Price")[
    [
        "Suburb",
        "Street_Number",
        "Street_Name",
        "Land Size",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
]

,Suburb,Street_Number,Street_Name,Land Size,Sale_Price,Property_type,Zoning
122,Chatswood,8,MCCABE PL,1416.00,7400000,COMMERCIAL,E4
50,Chatswood,11,HERCULES ST,1067.35,4600000,RESIDENCE,R2
98,Chatswood,71 B,EDDY RD,435.20,4420000,RESIDENCE,R2
51,Chatswood,10,HOLLAND ST,657.60,4080000,RESIDENCE,R2
96,Chatswood,15,ELLIS ST,178.00,4050000,RESIDENCE,

In [29]:
df["Property_type"].value_counts(dropna=False)

Property_type
RESIDENCE      122
COMMERCIAL       5
VACANT LAND      4
OFFICE           1
Name: count, dtype: int64

In [30]:
pd.crosstab(
    df["Suburb"],
    df["Property_type"]
)

Property_type  COMMERCIAL  OFFICE  RESIDENCE  VACANT LAND
Suburb
Blacktown               1       0         45            4
Chatswood               3       1         37            0
Parramatta              1       0         40            0

In [31]:
df[df["Property_type"] == "VACANT LAND"][
    [
        "Suburb",
        "Street_Number",
        "Street_Name",
        "Land Size",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
]

,Suburb,Street_Number,Street_Name,Land Size,Sale_Price,Property_type,Zoning
2,Blacktown,105,SUNNYHOLT RD,506.5,2079000,VACANT LAND,R4
3,Blacktown,107,SUNNYHOLT RD,336.9,2079000,VACANT LAND,R4
4,Blacktown,109,SUNNYHOLT RD,336.3,2079000,VACANT LAND,R4
5,Blacktown,111,SUNNYHOLT RD,335.6,2079000,VACANT LAND,R4

In [32]:
df_model = df[
    df["Property_type"] == "RESIDENCE"
].copy()

print("Raw records:", len(df))
print("Residential records:", len(df_model))

Raw records: 132
Residential records: 122

In [33]:
df_model["Suburb"].value_counts()

Suburb
Blacktown     45
Parramatta    40
Chatswood     37
Name: count, dtype: int64

In [35]:
duplicate_dealings = (
    df_model["Dealing_Number"]
    .value_counts()
)

duplicate_dealings[duplicate_dealings > 1]
df_model[
    df_model["Dealing_Number"].isin(
        duplicate_dealings[duplicate_dealings > 1].index
    )
][
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Land Size",
        "Contract_Date",
        "Settlement_Date",
        "Sale_Price",
        "Property_type",
        "Dealing_Number"
    ]
].sort_values("Dealing_Number")

Empty DataFrame
Columns: [Property_ID_Raw, Street_Number, Street_Name, Suburb, Land Size, Contract_Date, Settlement_Date, Sale_Price, Property_type, Dealing_Number]
Index: []

In [36]:
duplicate_addresses = df_model[
    df_model.duplicated(
        subset=["Street_Number", "Street_Name", "Suburb"],
        keep=False
    )
]

print("Duplicate address records:", len(duplicate_addresses))

duplicate_addresses[
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Land Size",
        "Contract_Date",
        "Sale_Price",
        "Property_type"
    ]
].sort_values(
    ["Suburb", "Street_Name", "Street_Number"]
)

Duplicate address records: 32

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Land Size,Contract_Date,Sale_Price,Property_type
6,6066721,9,HIGHLANDS CRES,Blacktown,238.0,2025-03-29,950000,RESIDENCE
24,6066721,9,HIGHLANDS CRES,Blacktown,258.0,2025-04-08,993000,RESIDENCE
39,2203406,25,MANTAKA ST,Blacktown,NaN,2026-06-21,425000,RESIDENCE
40,2203406,25,MANTAKA ST,Blacktown,NaN,2026-06-25,423000,RESIDENCE
30,3234330,8,WALLACE ST,Blacktown,NaN,2026-07-01,491000,RESIDENCE
46,3234330,8,WALLACE ST,Blacktown,NaN,2026-06-21,442000,RESIDENCE
47,3234330,8,WALLACE ST,Blacktown,NaN,2026-06-19,465000,RESIDENCE
87,6041724,15,ELLIS ST,Chatswood,105.0,2022-10-20,1705000,RESIDENCE
88,6041724,15,ELLIS ST,Chatswood,185.0,2022-10-27,2700000,RESIDENCE
89,6041724,15,ELLIS ST,Chatswood,181.0,2022-10-18,2495000,RESIDENCE
90,6041724,15,ELLIS ST,Chatswood,154.0,2022-10-21,2795000,RESIDENCE
91,6041724,15,ELLIS ST,Chatswood,111.0,2023-01-17,2150000,RESIDENCE
92,6041724,15,ELLIS ST,Chatswood,143.0,2024-05-24,3100000,RESIDENCE
93,6041724,15,ELLIS ST,Chatswood,111.0,2023-10-23,2250000,RESIDENCE
94,6041724,15,ELLIS ST,Chatswood,155.0,2022-10-19,3245000,RESIDENCE
95,6041724,15,ELLIS ST,Chatswood,156.0,2022-10-20,2950000,RESIDENCE
96,6041724,15,ELLIS ST,Chatswood,178.0,2022-10-24,4050000,RESIDENCE
97,6041724,15,ELLIS ST,Chatswood,162.0,2023-04-20,3850000,RESIDENCE
121,6041724,15,ELLIS ST,Chatswood,115.0,2026-06-26,1830000,RESIDENCE
85,4288822,88,CHURCH ST,Parramatta,106.0,2026-06-30,830000,RESIDENCE
119,4284539,88,CHURCH ST,Parramatta,65.0,2026-06-29,520000,RESIDENCE
80,4430759,180,GEORGE ST,Parramatta,70.0,2026-06-22,600000,RESIDENCE
81,4498625,180,GEORGE ST,Parramatta,122.0,2026-05-29,400000,RESIDENCE
112,4430759,180,GEORGE ST,Parramatta,89.0,2026-05-12,840000,RESIDENCE
113,4430759,180,GEORGE ST,Parramatta,109.0,2026-07-15,880000,RESIDENCE
114,4430759,180,GEORGE ST,Parramatta,103.0,2026-07-11,832000,RESIDENCE
83,3986285,45,MACQUARIE ST,Parramatta,NaN,2026-07-01,572000,RESIDENCE
84,3986285,45,MACQUARIE ST,Parramatta,NaN,2026-06-26,560000,RESIDENCE
82,3968952,1 A,MORTON ST,Parramatta,NaN,2026-06-27,680000,RESIDENCE
116,3968952,1 A,MORTON ST,Parramatta,NaN,2026-06-22,505000,RESIDENCE
67,4395676,12,PHILLIP ST,Parramatta,105.0,2026-08-07,1025000,RESIDENCE
68,4395676,12,PHILLIP ST,Parramatta,84.0,2026-07-08,780000,RESIDENCE

In [37]:
df_model.isnull().sum()

Property_ID_Raw     0
Sale_Counter        0
Street_Number       0
Street_Name         0
Suburb              0
Postcode            0
Land Size          53
Contract_Date       0
Settlement_Date     0
Sale_Price          0
Zoning              0
Property_type       0
Dealing_Number      0
dtype: int64

In [39]:
missing_land = (
    df_model["Land Size"].isna()
    .groupby(df_model["Suburb"])
    .sum()
)

missing_land
land_summary = df_model.groupby("Suburb")["Land Size"].agg(
    ["count", "median", "mean", "min", "max"]
)

land_summary

            count  median        mean    min     max
Suburb
Blacktown      29   556.4  470.305517  101.0   866.3
Chatswood      26   170.0  371.376923  105.0  1397.0
Parramatta     14   104.5  105.928571   65.0   192.0

In [40]:
print("Total residential records:", len(df_model))
print("Land size available:", df_model["Land Size"].notna().sum())
print("Land size missing:", df_model["Land Size"].isna().sum())

Total residential records: 122
Land size available: 69
Land size missing: 53

In [41]:
missing_land_by_suburb = df_model.groupby("Suburb")["Land Size"].apply(
    lambda x: x.isna().sum()
)

missing_land_by_suburb

Suburb
Blacktown     16
Chatswood     11
Parramatta    26
Name: Land Size, dtype: int64

In [42]:
land_availability = df_model.groupby("Suburb")["Land Size"].apply(
    lambda x: x.notna().sum()
)

land_availability

Suburb
Blacktown     29
Chatswood     26
Parramatta    14
Name: Land Size, dtype: int64

In [43]:
df_model["Land Size"].describe()

count      69.000000
mean      359.096522
std       303.870667
min        65.000000
25%       111.000000
50%       185.000000
75%       557.330000
max      1397.000000
Name: Land Size, dtype: float64

In [45]:
df_model["Contract_Date"] = pd.to_datetime(
    df_model["Contract_Date"],
    errors="coerce"
)

df_model["Settlement_Date"] = pd.to_datetime(
    df_model["Settlement_Date"],
    errors="coerce"
)

print("Earliest contract date:", df_model["Contract_Date"].min())
print("Latest contract date:", df_model["Contract_Date"].max())

print("Earliest settlement date:", df_model["Settlement_Date"].min())
print("Latest settlement date:", df_model["Settlement_Date"].max())

Earliest contract date: 2022-10-18 00:00:00
Latest contract date: 2026-08-07 00:00:00
Earliest settlement date: 2026-04-01 00:00:00
Latest settlement date: 2026-08-20 00:00:00

In [46]:
df_model["Contract_Year"] = df_model["Contract_Date"].dt.year

df_model["Contract_Year"].value_counts().sort_index()

Contract_Year
2022      7
2023      3
2024      1
2025      3
2026    108
Name: count, dtype: int64

In [47]:
df_model.groupby(
    ["Suburb", "Contract_Year"]
)["Sale_Price"].agg(["count", "median", "mean"])

                          count     median          mean
Suburb     Contract_Year
Blacktown  2025               3   993000.0  1.146000e+06
           2026              42   860000.0  8.413095e+05
Chatswood  2022               7  2795000.0  2.848571e+06
           2023               3  2250000.0  2.750000e+06
           2024               1  3100000.0  3.100000e+06
           2026              26  2235000.0  2.154846e+06
Parramatta 2026              40   612500.0  6.282028e+05

In [48]:
df_model["Days_to_Settlement"] = (
    df_model["Settlement_Date"] -
    df_model["Contract_Date"]
).dt.days

df_model.nlargest(10, "Days_to_Settlement")[
    [
        "Suburb",
        "Street_Number",
        "Street_Name",
        "Contract_Date",
        "Settlement_Date",
        "Days_to_Settlement",
        "Sale_Price",
        "Property_type"
    ]
]

,Suburb,Street_Number,Street_Name,Contract_Date,Settlement_Date,Days_to_Settlement,Sale_Price,Property_type
89,Chatswood,15,ELLIS ST,2022-10-18,2026-05-25,1315,2495000,RESIDENCE
94,Chatswood,15,ELLIS ST,2022-10-19,2026-05-25,1314,3245000,RESIDENCE
87,Chatswood,15,ELLIS ST,2022-10-20,2026-05-25,1313,1705000,RESIDENCE
95,Chatswood,15,ELLIS ST,2022-10-20,2026-05-25,1313,2950000,RESIDENCE
90,Chatswood,15,ELLIS ST,2022-10-21,2026-05-25,1312,2795000,RESIDENCE
96,Chatswood,15,ELLIS ST,2022-10-24,2026-05-25,1309,4050000,RESIDENCE
88,Chatswood,15,ELLIS ST,2022-10-27,2026-05-27,1308,2700000,RESIDENCE
91,Chatswood,15,ELLIS ST,2023-01-17,2026-05-25,1224,2150000,RESIDENCE
97,Chatswood,15,ELLIS ST,2023-04-20,2026-05-25,1131,3850000,RESIDENCE
93,Chatswood,15,ELLIS ST,2023-10-23,2026-05-25,945,2250000,RESIDENCE

In [49]:
df_model[
    (df_model["Street_Number"] == "15") &
    (df_model["Street_Name"].str.strip() == "ELLIS ST")
][[
    "Property_ID_Raw",
    "Street_Number",
    "Street_Name",
    "Suburb",
    "Land Size",
    "Contract_Date",
    "Settlement_Date",
    "Sale_Price",
    "Property_type",
    "Zoning",
    "Dealing_Number"
]].sort_values("Contract_Date")

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Land Size,Contract_Date,Settlement_Date,Sale_Price,Property_type,Zoning,Dealing_Number
89,6041724,15,ELLIS ST,Chatswood,181.0,2022-10-18,2026-05-25,2495000,RESIDENCE,,AW151200
94,6041724,15,ELLIS ST,Chatswood,155.0,2022-10-19,2026-05-25,3245000,RESIDENCE,,AW151106
87,6041724,15,ELLIS ST,Chatswood,105.0,2022-10-20,2026-05-25,1705000,RESIDENCE,,AW151132
95,6041724,15,ELLIS ST,Chatswood,156.0,2022-10-20,2026-05-25,2950000,RESIDENCE,,AW151072
90,6041724,15,ELLIS ST,Chatswood,154.0,2022-10-21,2026-05-25,2795000,RESIDENCE,,AW150924
96,6041724,15,ELLIS ST,Chatswood,178.0,2022-10-24,2026-05-25,4050000,RESIDENCE,,AW151004
88,6041724,15,ELLIS ST,Chatswood,185.0,2022-10-27,2026-05-27,2700000,RESIDENCE,,AW158589
91,6041724,15,ELLIS ST,Chatswood,111.0,2023-01-17,2026-05-25,2150000,RESIDENCE,,AW151509
97,6041724,15,ELLIS ST,Chatswood,162.0,2023-04-20,2026-05-25,3850000,RESIDENCE,,AW151094
93,6041724,15,ELLIS ST,Chatswood,111.0,2023-10-23,2026-05-25,2250000,RESIDENCE,,AW151090
92,6041724,15,ELLIS ST,Chatswood,143.0,2024-05-24,2026-06-03,3100000,RESIDENCE,,AW180731
121,6041724,15,ELLIS ST,Chatswood,115.0,2026-06-26,2026-08-07,1830000,RESIDENCE,,AW360414

In [50]:
df_model["Contract_Year"] = df_model["Contract_Date"].dt.year

df_model["Contract_Year"].value_counts().sort_index()

Contract_Year
2022      7
2023      3
2024      1
2025      3
2026    108
Name: count, dtype: int64

In [51]:
df_model["Contract_Year"] = df_model["Contract_Date"].dt.year

df_model["Contract_Year"].value_counts().sort_index()

Contract_Year
2022      7
2023      3
2024      1
2025      3
2026    108
Name: count, dtype: int64

In [52]:
df_model.groupby(
    ["Suburb", "Contract_Year"]
)["Sale_Price"].agg(
    ["count", "median", "mean"]
)

                          count     median          mean
Suburb     Contract_Year
Blacktown  2025               3   993000.0  1.146000e+06
           2026              42   860000.0  8.413095e+05
Chatswood  2022               7  2795000.0  2.848571e+06
           2023               3  2250000.0  2.750000e+06
           2024               1  3100000.0  3.100000e+06
           2026              26  2235000.0  2.154846e+06
Parramatta 2026              40   612500.0  6.282028e+05

In [53]:
df_model["Sale_Price"].describe()

count    1.220000e+02
mean     1.239485e+06
std      9.945450e+05
min      3.120000e+05
25%      5.705000e+05
50%      8.400000e+05
75%      1.385000e+06
max      4.600000e+06
Name: Sale_Price, dtype: float64

In [54]:
df_model.nlargest(10, "Sale_Price")[
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Land Size",
        "Contract_Date",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
]

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Land Size,Contract_Date,Sale_Price,Property_type,Zoning
50,960871,11,HERCULES ST,Chatswood,1067.35,2026-06-06,4600000,RESIDENCE,R2
98,6059657,71 B,EDDY RD,Chatswood,435.20,2026-07-20,4420000,RESIDENCE,R2
51,961369,10,HOLLAND ST,Chatswood,657.60,2026-05-07,4080000,RESIDENCE,R2
96,6041724,15,ELLIS ST,Chatswood,178.00,2022-10-24,4050000,RESIDENCE,
97,6041724,15,ELLIS ST,Chatswood,162.00,2023-04-20,3850000,RESIDENCE,
126,960958,274,HIGH ST,Chatswood,520.15,2026-06-30,3510000,RESIDENCE,R2
94,6041724,15,ELLIS ST,Chatswood,155.00,2022-10-19,3245000,RESIDENCE,
123,951381,91,BEACONSFIELD RD,Chatswood,736.50,2026-07-28,3200000,RESIDENCE,R2
92,6041724,15,ELLIS ST,Chatswood,143.00,2024-05-24,3100000,RESIDENCE,
100,958731,5,GIBBES ST,Chatswood,1170.00,2026-03-12,3100000,RESIDENCE,E4

In [55]:
df_model["Sale_Price"].describe()

count    1.220000e+02
mean     1.239485e+06
std      9.945450e+05
min      3.120000e+05
25%      5.705000e+05
50%      8.400000e+05
75%      1.385000e+06
max      4.600000e+06
Name: Sale_Price, dtype: float64

In [56]:
df_model.nlargest(10, "Sale_Price")[
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Land Size",
        "Contract_Date",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
]

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Land Size,Contract_Date,Sale_Price,Property_type,Zoning
50,960871,11,HERCULES ST,Chatswood,1067.35,2026-06-06,4600000,RESIDENCE,R2
98,6059657,71 B,EDDY RD,Chatswood,435.20,2026-07-20,4420000,RESIDENCE,R2
51,961369,10,HOLLAND ST,Chatswood,657.60,2026-05-07,4080000,RESIDENCE,R2
96,6041724,15,ELLIS ST,Chatswood,178.00,2022-10-24,4050000,RESIDENCE,
97,6041724,15,ELLIS ST,Chatswood,162.00,2023-04-20,3850000,RESIDENCE,
126,960958,274,HIGH ST,Chatswood,520.15,2026-06-30,3510000,RESIDENCE,R2
94,6041724,15,ELLIS ST,Chatswood,155.00,2022-10-19,3245000,RESIDENCE,
123,951381,91,BEACONSFIELD RD,Chatswood,736.50,2026-07-28,3200000,RESIDENCE,R2
92,6041724,15,ELLIS ST,Chatswood,143.00,2024-05-24,3100000,RESIDENCE,
100,958731,5,GIBBES ST,Chatswood,1170.00,2026-03-12,3100000,RESIDENCE,E4

In [57]:
df_model.nsmallest(10, "Sale_Price")[
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Land Size",
        "Contract_Date",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
]

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Land Size,Contract_Date,Sale_Price,Property_type,Zoning
76,2842977,3,VALENTINE AVE,Parramatta,NaN,2026-05-20,312000,RESIDENCE,
61,853048,11,VILLIERS ST,Parramatta,NaN,2026-06-18,350000,RESIDENCE,
62,3000848,32,HASSALL ST,Parramatta,NaN,2026-07-10,350000,RESIDENCE,
81,4498625,180,GEORGE ST,Parramatta,122.0,2026-05-29,400000,RESIDENCE,
63,3181871,31,HASSALL ST,Parramatta,NaN,2026-07-03,404000,RESIDENCE,
11,2185346,7,GRIFFITHS ST,Blacktown,NaN,2026-07-09,410000,RESIDENCE,
45,3166844,20,CLIFTON ST,Blacktown,NaN,2026-06-24,410000,RESIDENCE,
70,813176,15,CAMPBELL ST,Parramatta,NaN,2026-07-02,411000,RESIDENCE,
33,3293974,19,THIRD AVE,Blacktown,NaN,2026-06-30,415000,RESIDENCE,
0,3410896,31,THIRD AVE,Blacktown,NaN,2026-07-05,420000,RESIDENCE,

In [58]:
Q1 = df_model["Sale_Price"].quantile(0.25)
Q3 = df_model["Sale_Price"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 570500.0
Q3: 1385000.0
IQR: 814500.0
Lower bound: -651250.0
Upper bound: 2606750.0

In [59]:
price_outliers = df_model[
    (df_model["Sale_Price"] < lower_bound) |
    (df_model["Sale_Price"] > upper_bound)
]

print("Potential price outliers:", len(price_outliers))

price_outliers[
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Land Size",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
].sort_values("Sale_Price")

Potential price outliers: 16

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Land Size,Sale_Price,Property_type,Zoning
57,3343003,1,CAMBRIDGE LANE,Chatswood,NaN,2628000,RESIDENCE,
88,6041724,15,ELLIS ST,Chatswood,185.00,2700000,RESIDENCE,
124,954176,28,CLAUDE ST,Chatswood,NaN,2750000,RESIDENCE,
90,6041724,15,ELLIS ST,Chatswood,154.00,2795000,RESIDENCE,
95,6041724,15,ELLIS ST,Chatswood,156.00,2950000,RESIDENCE,
92,6041724,15,ELLIS ST,Chatswood,143.00,3100000,RESIDENCE,
100,958731,5,GIBBES ST,Chatswood,1170.00,3100000,RESIDENCE,E4
102,971187,5,SPENCER PL,Chatswood,714.50,3100000,RESIDENCE,R2
123,951381,91,BEACONSFIELD RD,Chatswood,736.50,3200000,RESIDENCE,R2
94,6041724,15,ELLIS ST,Chatswood,155.00,3245000,RESIDENCE,
126,960958,274,HIGH ST,Chatswood,520.15,3510000,RESIDENCE,R2
97,6041724,15,ELLIS ST,Chatswood,162.00,3850000,RESIDENCE,
96,6041724,15,ELLIS ST,Chatswood,178.00,4050000,RESIDENCE,
51,961369,10,HOLLAND ST,Chatswood,657.60,4080000,RESIDENCE,R2
98,6059657,71 B,EDDY RD,Chatswood,435.20,4420000,RESIDENCE,R2
50,960871,11,HERCULES ST,Chatswood,1067.35,4600000,RESIDENCE,R2

In [60]:
# Check missing Land Size records

missing_land = df_model[df_model["Land Size"].isna()]

print("Missing Land Size records:", len(missing_land))

missing_land[
    [
        "Property_ID_Raw",
        "Street_Number",
        "Street_Name",
        "Suburb",
        "Sale_Price",
        "Property_type",
        "Zoning"
    ]
].head(20)

Missing Land Size records: 53

,Property_ID_Raw,Street_Number,Street_Name,Suburb,Sale_Price,Property_type,Zoning
0,3410896,31,THIRD AVE,Blacktown,420000,RESIDENCE,
11,2185346,7,GRIFFITHS ST,Blacktown,410000,RESIDENCE,
12,2180221,313,FLUSHCOMBE RD,Blacktown,920000,RESIDENCE,
15,2181097,25,FOURTH AVE,Blacktown,463000,RESIDENCE,
27,2213533,67,ORWELL ST,Blacktown,840000,RESIDENCE,
29,3198476,21,THIRD AVE,Blacktown,420000,RESIDENCE,
30,3234330,8,WALLACE ST,Blacktown,491000,RESIDENCE,
32,2195139,25,KILDARE RD,Blacktown,470000,RESIDENCE,
33,3293974,19,THIRD AVE,Blacktown,415000,RESIDENCE,
39,2203406,25,MANTAKA ST,Blacktown,425000,RESIDENCE,
40,2203406,25,MANTAKA ST,Blacktown,423000,RESIDENCE,
44,2220985,177,RESERVOIR RD,Blacktown,635000,RESIDENCE,
45,3166844,20,CLIFTON ST,Blacktown,410000,RESIDENCE,
46,3234330,8,WALLACE ST,Blacktown,442000,RESIDENCE,
47,3234330,8,WALLACE ST,Blacktown,465000,RESIDENCE,
48,3311689,69,HOLBECHE RD,Blacktown,680000,RESIDENCE,
52,971886,4,SUTHERLAND RD,Chatswood,1460000,RESIDENCE,
56,2893078,2 B,HELP ST,Chatswood,800000,RESIDENCE,
57,3343003,1,CAMBRIDGE LANE,Chatswood,2628000,RESIDENCE,
59,819187,15,EARLY ST,Parramatta,588000,RESIDENCE,

In [63]:
df_model["Land Size Original"] = df_model["Land Size"]

df_model["Land Size"] = df_model.groupby("Suburb")["Land Size"].transform(
    lambda x: x.fillna(x.median())
)

print("Missing Land Size after imputation:",
      df_model["Land Size"].isna().sum())

Missing Land Size after imputation: 0

In [64]:
df_model.groupby("Suburb")["Land Size"].agg(
    ["count", "mean", "median", "min", "max"]
)

            count        mean  median    min     max
Suburb
Blacktown      45  500.916889   556.4  101.0   866.3
Chatswood      37  311.508108   170.0  105.0  1397.0
Parramatta     40  105.000000   104.5   65.0   192.0

In [65]:
df_model[
    ["Suburb", "Land Size Original", "Land Size"]
].head(20)

       Suburb  Land Size Original  Land Size
0   Blacktown              556.40     556.40
1   Blacktown              104.00     104.00
6   Blacktown              238.00     238.00
7   Blacktown              512.00     512.00
8   Blacktown              556.40     556.40
9   Blacktown              689.20     689.20
10  Blacktown              765.10     765.10
11  Blacktown              556.40     556.40
12  Blacktown              556.40     556.40
13  Blacktown              608.53     608.53
14  Blacktown              101.00     101.00
15  Blacktown              556.40     556.40
16  Blacktown              557.33     557.33
17  Blacktown              696.77     696.77
18  Blacktown              556.40     556.40
19  Blacktown              701.90     701.90
20  Blacktown              556.40     556.40
21  Blacktown              300.00     300.00
22  Blacktown              103.00     103.00
23  Blacktown              111.00     111.00

In [66]:
# Create the initial modelling dataset

model_columns = [
    "Suburb",
    "Land Size",
    "Contract_Date",
    "Zoning",
    "Sale_Price"
]

df_ml = df_model[model_columns].copy()

print("ML dataset shape:", df_ml.shape)
print("\nColumns:")
print(df_ml.columns.tolist())

ML dataset shape: (122, 5)

Columns:
['Suburb', 'Land Size', 'Contract_Date', 'Zoning', 'Sale_Price']

In [67]:
# Create the initial modelling dataset

model_columns = [
    "Suburb",
    "Land Size",
    "Contract_Date",
    "Zoning",
    "Sale_Price"
]

df_ml = df_model[model_columns].copy()

print("ML dataset shape:", df_ml.shape)
print("\nColumns:")
print(df_ml.columns.tolist())

ML dataset shape: (122, 5)

Columns:
['Suburb', 'Land Size', 'Contract_Date', 'Zoning', 'Sale_Price']

In [68]:
# Convert Contract_Date to datetime
df_ml["Contract_Date"] = pd.to_datetime(
    df_ml["Contract_Date"],
    errors="coerce"
)

# Extract useful date features
df_ml["Contract_Year"] = df_ml["Contract_Date"].dt.year
df_ml["Contract_Month"] = df_ml["Contract_Date"].dt.month

# Check the result
print(df_ml[[
    "Contract_Date",
    "Contract_Year",
    "Contract_Month"
]].head(10))

   Contract_Date  Contract_Year  Contract_Month
0     2026-07-05           2026               7
1     2026-07-05           2026               7
6     2025-03-29           2025               3
7     2025-11-07           2025              11
8     2026-07-06           2026               7
9     2026-07-05           2026               7
10    2026-07-07           2026               7
11    2026-07-09           2026               7
12    2026-07-10           2026               7
13    2026-07-25           2026               7

In [69]:
print(df_ml["Contract_Year"].value_counts().sort_index())

Contract_Year
2022      7
2023      3
2024      1
2025      3
2026    108
Name: count, dtype: int64

In [70]:
df_ml = df_ml.drop(columns=["Contract_Date"])

print(df_ml.head())
print("\nShape:", df_ml.shape)

      Suburb  Land Size Zoning  Sale_Price  Contract_Year  Contract_Month
0  Blacktown      556.4             420000           2026               7
1  Blacktown      104.0             600000           2026               7
6  Blacktown      238.0             950000           2025               3
7  Blacktown      512.0     R2     1495000           2025              11
8  Blacktown      556.4     R2     1110000           2026               7

Shape: (122, 6)

In [71]:
# Check missing values in the ML dataset

print(df_ml.isnull().sum())

Suburb            0
Land Size         0
Zoning            0
Sale_Price        0
Contract_Year     0
Contract_Month    0
dtype: int64

In [72]:
print("\nData types:")
print(df_ml.dtypes)

Data types:
Suburb             object
Land Size         float64
Zoning             object
Sale_Price          int64
Contract_Year       int32
Contract_Month      int32
dtype: object

In [74]:
from sklearn.preprocessing import OneHotEncoder

# Create encoder
encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

# Encode categorical columns
encoded = encoder.fit_transform(
    df_ml[["Suburb", "Zoning"]]
)

# Get encoded column names
encoded_columns = encoder.get_feature_names_out(
    ["Suburb", "Zoning"]
)

# Create DataFrame
df_encoded = pd.DataFrame(
    encoded,
    columns=encoded_columns,
    index=df_ml.index
)

# Combine numerical columns with encoded columns
df_final = pd.concat(
    [
        df_ml[[
            "Land Size",
            "Contract_Year",
            "Contract_Month",
            "Sale_Price"
        ]],
        df_encoded
    ],
    axis=1
)

print("Final dataset shape:", df_final.shape)
print("\nColumns:")
print(df_final.columns.tolist())
print(df_final.head())

Final dataset shape: (122, 12)

Columns:
['Land Size', 'Contract_Year', 'Contract_Month', 'Sale_Price', 'Suburb_Blacktown', 'Suburb_Chatswood', 'Suburb_Parramatta', 'Zoning_', 'Zoning_C4', 'Zoning_E4', 'Zoning_R1', 'Zoning_R2']
   Land Size  Contract_Year  Contract_Month  Sale_Price  Suburb_Blacktown  \
0      556.4           2026               7      420000               1.0
1      104.0           2026               7      600000               1.0
6      238.0           2025               3      950000               1.0
7      512.0           2025              11     1495000               1.0
8      556.4           2026               7     1110000               1.0

   Suburb_Chatswood  Suburb_Parramatta  Zoning_  Zoning_C4  Zoning_E4  \
0               0.0                0.0      1.0        0.0        0.0
1               0.0                0.0      1.0        0.0        0.0
6               0.0                0.0      1.0        0.0        0.0
7               0.0                0.0      0.0        0.0        0.0
8               0.0                0.0      0.0        0.0        0.0

   Zoning_R1  Zoning_R2
0        0.0        0.0
1        0.0        0.0
6        0.0        0.0
7        0.0        1.0
8        0.0        1.0

In [75]:
# Separate features and target

X = df_final.drop(columns=["Sale_Price"])
y = df_final["Sale_Price"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeature columns:")
print(X.columns.tolist())

X shape: (122, 11)
y shape: (122,)

Feature columns:
['Land Size', 'Contract_Year', 'Contract_Month', 'Suburb_Blacktown', 'Suburb_Chatswood', 'Suburb_Parramatta', 'Zoning_', 'Zoning_C4', 'Zoning_E4', 'Zoning_R1', 'Zoning_R2']

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training X shape:", X_train.shape)
print("Testing X shape:", X_test.shape)
print("Training y shape:", y_train.shape)
print("Testing y shape:", y_test.shape)

Training X shape: (97, 11)
Testing X shape: (25, 11)
Training y shape: (97,)
Testing y shape: (25,)

In [77]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Create the model
linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train, y_train)

# Make predictions
y_pred = linear_model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Linear Regression Results")
print("-------------------------")
print("MAE :", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R²  :", round(r2, 4))

Linear Regression Results
-------------------------
MAE : 437716.38
RMSE: 652333.23
R²  : 0.7292

In [78]:
df_model.to_csv("Sydney_Housing_ML_Dataset.csv", index=False)

print("CSV saved successfully!")
print("Shape:", df_model.shape)

CSV saved successfully!
Shape: (122, 16)

In [79]:
import os

print(os.path.abspath("Sydney_Housing_ML_Dataset.csv"))
print(os.path.getsize("Sydney_Housing_ML_Dataset.csv"), "bytes")

/Users/souravchoudhary/Sydney_Housing_Project.ipynb/Sydney_Housing_ML_Dataset.csv
13650 bytes

In [80]:
import os

print(os.getcwd())
print(os.listdir())

/Users/souravchoudhary/Sydney_Housing_Project.ipynb
['157_SALES_DATA_NNME_17082026.DAT', '159_SALES_DATA_NNME_17082026.DAT', '151_SALES_DATA_NNME_10082026.DAT', '230_SALES_DATA_NNME_24082026.DAT', '144_SALES_DATA_NNME_10082026.DAT', '255_SALES_DATA_NNME_17082026.DAT', '051_SALES_DATA_NNME_24082026.DAT', '271_SALES_DATA_NNME_17082026.DAT', '301_SALES_DATA_NNME_10082026.DAT', '538_SALES_DATA_NNME_17082026.DAT', '018_SALES_DATA_NNME_10082026.DAT', '214_SALES_DATA_NNME_24082026.DAT', '088_SALES_DATA_NNME_17082026.DAT', '103_SALES_DATA_NNME_24082026.DAT', '010_SALES_DATA_NNME_17082026.DAT', '005_SALES_DATA_NNME_17082026.DAT', '262_SALES_DATA_NNME_10082026.DAT', '116_SALES_DATA_NNME_24082026.DAT', '118_SALES_DATA_NNME_24082026.DAT', '264_SALES_DATA_NNME_17082026.DAT', '258_SALES_DATA_NNME_24082026.DAT', '511_SALES_DATA_NNME_24082026.DAT', '608_SALES_DATA_NNME_24082026.DAT', '124_SALES_DATA_NNME_17082026.DAT', '054_SALES_DATA_NNME_10082026.DAT', '233_SALES_DATA_NNME_17082026.DAT', '226_SALES_DATA_NNME_17082026.DAT', '708_SALES_DATA_NNME_10082026.DAT', '137_SALES_DATA_NNME_10082026.DAT', '243_SALES_DATA_NNME_24082026.DAT', '220_SALES_DATA_NNME_10082026.DAT', '139_SALES_DATA_NNME_10082026.DAT', '267_SALES_DATA_NNME_24082026.DAT', '269_SALES_DATA_NNME_24082026.DAT', '090_SALES_DATA_NNME_24082026.DAT', '065_SALES_DATA_NNME_10082026.DAT', '008_SALES_DATA_NNME_24082026.DAT', '219_SALES_DATA_NNME_17082026.DAT', '100_SALES_DATA_NNME_17082026.DAT', '217_SALES_DATA_NNME_17082026.DAT', '085_SALES_DATA_NNME_24082026.DAT', '070_SALES_DATA_NNME_10082026.DAT', '272_SALES_DATA_NNME_24082026.DAT', '240_SALES_DATA_NNME_24082026.DAT', '159_SALES_DATA_NNME_24082026.DAT', '223_SALES_DATA_NNME_10082026.DAT', '157_SALES_DATA_NNME_24082026.DAT', '042_SALES_DATA_NNME_10082026.DAT', '230_SALES_DATA_NNME_17082026.DAT', '236_SALES_DATA_NNME_10082026.DAT', '051_SALES_DATA_NNME_17082026.DAT', '238_SALES_DATA_NNME_10082026.DAT', '666_SALES_DATA_NNME_10082026.DAT', '255_SALES_DATA_NNME_24082026.DAT', '538_SALES_DATA_NNME_24082026.DAT', '271_SALES_DATA_NNME_24082026.DAT', '088_SALES_DATA_NNME_24082026.DAT', '103_SALES_DATA_NNME_17082026.DAT', '010_SALES_DATA_NNME_24082026.DAT', '214_SALES_DATA_NNME_17082026.DAT', '118_SALES_DATA_NNME_17082026.DAT', '066_SALES_DATA_NNME_10082026.DAT', '005_SALES_DATA_NNME_24082026.DAT', '116_SALES_DATA_NNME_17082026.DAT', '188_SALES_DATA_NNME_10082026.DAT', '209_SALES_DATA_NNME_10082026.DAT', '264_SALES_DATA_NNME_24082026.DAT', '207_SALES_DATA_NNME_10082026.DAT', '511_SALES_DATA_NNME_17082026.DAT', '608_SALES_DATA_NNME_17082026.DAT', '052_SALES_DATA_NNME_24082026.DAT', '258_SALES_DATA_NNME_17082026.DAT', '233_SALES_DATA_NNME_24082026.DAT', '124_SALES_DATA_NNME_24082026.DAT', '250_SALES_DATA_NNME_10082026.DAT', '149_SALES_DATA_NNME_10082026.DAT', '226_SALES_DATA_NNME_24082026.DAT', '152_SALES_DATA_NNME_10082026.DAT', '243_SALES_DATA_NNME_17082026.DAT', '269_SALES_DATA_NNME_17082026.DAT', '267_SALES_DATA_NNME_17082026.DAT', '098_SALES_DATA_NNME_10082026.DAT', '261_SALES_DATA_NNME_10082026.DAT', '526_SALES_DATA_NNME_10082026.DAT', '528_SALES_DATA_NNME_10082026.DAT', '090_SALES_DATA_NNME_17082026.DAT', '008_SALES_DATA_NNME_17082026.DAT', '217_SALES_DATA_NNME_24082026.DAT', '085_SALES_DATA_NNME_17082026.DAT', '219_SALES_DATA_NNME_24082026.DAT', '274_SALES_DATA_NNME_10082026.DAT', '100_SALES_DATA_NNME_24082026.DAT', '272_SALES_DATA_NNME_17082026.DAT', '302_SALES_DATA_NNME_10082026.DAT', '083_SALES_DATA_NNME_10082026.DAT', '188_SALES_DATA_NNME_17082026.DAT', '209_SALES_DATA_NNME_17082026.DAT', '207_SALES_DATA_NNME_17082026.DAT', 'Untitled.ipynb', 'Sydney_Housing_ML_Dataset.csv', '118_SALES_DATA_NNME_10082026.DAT', '066_SALES_DATA_NNME_17082026.DAT', '262_SALES_DATA_NNME_24082026.DAT', '116_SALES_DATA_NNME_10082026.DAT', '103_SALES_DATA_NNME_10082026.DAT', '214_SALES_DATA_NNME_10082026.DAT', '301_SALES_DATA_NNME_24082026.DAT', 'Sydney_Housing_ML_Model.ipynb', '018_SALES_DATA_NNME_24082026.DAT', '236_SALES_DATA_NNME_17082026.DAT', '051_SALES_DATA_NNME_10082026.DAT', '238_SALES_DATA_NNME_17082026.DAT', '666_SALES_DATA_NNME_17082026.DAT', '253_SALES_DATA_NNME_24082026.DAT', '230_SALES_DATA_NNME_10082026.DAT', '144_SALES_DATA_NNME_24082026.DAT', '042_SALES_DATA_NNME_17082026.DAT', '151_SALES_DATA_NNME_24082026.DAT', '223_SALES_DATA_NNME_17082026.DAT', '272_SALES_DATA_NNME_10082026.DAT', '302_SALES_DATA_NNME_17082026.DAT', '083_SALES_DATA_NNME_17082026.DAT', '085_SALES_DATA_NNME_10082026.DAT', '070_SALES_DATA_NNME_24082026.DAT', '274_SALES_DATA_NNME_17082026.DAT', '261_SALES_DATA_NNME_17082026.DAT', '526_SALES_DATA_NNME_17082026.DAT', '528_SALES_DATA_NNME_17082026.DAT', '090_SALES_DATA_NNME_10082026.DAT', '065_SALES_DATA_NNME_24082026.DAT', '008_SALES_DATA_NNME_10082026.DAT', '269_SALES_DATA_NNME_10082026.DAT', '267_SALES_DATA_NNME_10082026.DAT', '098_SALES_DATA_NNME_17082026.DAT', '220_SALES_DATA_NNME_24082026.DAT', '139_SALES_DATA_NNME_24082026.DAT', '137_SALES_DATA_NNME_24082026.DAT', '243_SALES_DATA_NNME_10082026.DAT', '708_SALES_DATA_NNME_24082026.DAT', '152_SALES_DATA_NNME_17082026.DAT', '054_SALES_DATA_NNME_24082026.DAT', '250_SALES_DATA_NNME_17082026.DAT', '149_SALES_DATA_NNME_17082026.DAT', '511_SALES_DATA_NNME_10082026.DAT', '608_SALES_DATA_NNME_10082026.DAT', '258_SALES_DATA_NNME_10082026.DAT', '235_SALES_DATA_NNME_24082026.DAT', '207_SALES_DATA_NNME_24082026.DAT', '209_SALES_DATA_NNME_24082026.DAT', '188_SALES_DATA_NNME_24082026.DAT', '264_SALES_DATA_NNME_10082026.DAT', '005_SALES_DATA_NNME_10082026.DAT', '262_SALES_DATA_NNME_17082026.DAT', '088_SALES_DATA_NNME_10082026.DAT', '010_SALES_DATA_NNME_10082026.DAT', '271_SALES_DATA_NNME_10082026.DAT', '301_SALES_DATA_NNME_17082026.DAT', '538_SALES_DATA_NNME_10082026.DAT', '018_SALES_DATA_NNME_17082026.DAT', '238_SALES_DATA_NNME_24082026.DAT', '666_SALES_DATA_NNME_24082026.DAT', '255_SALES_DATA_NNME_10082026.DAT', '236_SALES_DATA_NNME_24082026.DAT', '144_SALES_DATA_NNME_17082026.DAT', '042_SALES_DATA_NNME_24082026.DAT', '151_SALES_DATA_NNME_17082026.DAT', '223_SALES_DATA_NNME_24082026.DAT', '157_SALES_DATA_NNME_10082026.DAT', '240_SALES_DATA_NNME_10082026.DAT', '159_SALES_DATA_NNME_10082026.DAT', '083_SALES_DATA_NNME_24082026.DAT', '302_SALES_DATA_NNME_24082026.DAT', '219_SALES_DATA_NNME_10082026.DAT', '274_SALES_DATA_NNME_24082026.DAT', '100_SALES_DATA_NNME_10082026.DAT', '217_SALES_DATA_NNME_10082026.DAT', '070_SALES_DATA_NNME_17082026.DAT', '065_SALES_DATA_NNME_17082026.DAT', '528_SALES_DATA_NNME_24082026.DAT', '261_SALES_DATA_NNME_24082026.DAT', '526_SALES_DATA_NNME_24082026.DAT', '098_SALES_DATA_NNME_24082026.DAT', '137_SALES_DATA_NNME_17082026.DAT', '220_SALES_DATA_NNME_17082026.DAT', '139_SALES_DATA_NNME_17082026.DAT', '226_SALES_DATA_NNME_10082026.DAT', '152_SALES_DATA_NNME_24082026.DAT', '708_SALES_DATA_NNME_17082026.DAT', '124_SALES_DATA_NNME_10082026.DAT', '250_SALES_DATA_NNME_24082026.DAT', '149_SALES_DATA_NNME_24082026.DAT', '054_SALES_DATA_NNME_17082026.DAT', '052_SALES_DATA_NNME_10082026.DAT', '150_SALES_DATA_NNME_17082026.DAT', '043_SALES_DATA_NNME_24082026.DAT', '247_SALES_DATA_NNME_17082026.DAT', '158_SALES_DATA_NNME_10082026.DAT', '222_SALES_DATA_NNME_24082026.DAT', '143_SALES_DATA_NNME_10082026.DAT', '254_SALES_DATA_NNME_10082026.DAT', '239_SALES_DATA_NNME_24082026.DAT', '252_SALES_DATA_NNME_17082026.DAT', '276_SALES_DATA_NNME_17082026.DAT', '087_SALES_DATA_NNME_10082026.DAT', '620_SALES_DATA_NNME_10082026.DAT', '192_SALES_DATA_NNME_24082026.DAT', '081_SALES_DATA_NNME_17082026.DAT', '300_SALES_DATA_NNME_17082026.DAT', 'sydney_housing_random_forest.pkl', '537_SALES_DATA_NNME_10082026.DAT', '270_SALES_DATA_NNME_10082026.DAT', '265_SALES_DATA_NNME_10082026.DAT', '656_SALES_DATA_NNME_24082026.DAT', '002_SALES_DATA_NNME_17082026.DAT', '187_SALES_DATA_NNME_24082026.DAT', '092_SALES_DATA_NNME_10082026.DAT', '263_SALES_DATA_NNME_17082026.DAT', '004_SALES_DATA_NNME_10082026.DAT', '575_SALES_DATA_NNME_10082026.DAT', '232_SALES_DATA_NNME_10082026.DAT', '148_SALES_DATA_NNME_24082026.DAT', '251_SALES_DATA_NNME_24082026.DAT', '123_SALES_DATA_NNME_17082026.DAT', '234_SALES_DATA_NNME_17082026.DAT', '244_SALES_DATA_NNME_24082026.DAT', '560_SALES_DATA_NNME_10082026.DAT', '260_SALES_DATA_NNME_24082026.DAT', '529_SALES_DATA_NNME_24082026.DAT', 'model_features.pkl', '097_SALES_DATA_NNME_24082026.DAT', '001_SALES_DATA_NNME_24082026.DAT', '082_SALES_DATA_NNME_24082026.DAT', '303_SALES_DATA_NNME_24082026.DAT', '109_SALES_DATA_NNME_17082026.DAT', '210_SALES_DATA_NNME_17082026.DAT', '216_SALES_DATA_NNME_10082026.DAT', '275_SALES_DATA_NNME_24082026.DAT', '101_SALES_DATA_NNME_10082026.DAT', '218_SALES_DATA_NNME_10082026.DAT', '199_SALES_DATA_NNME_10082026.DAT', '247_SALES_DATA_NNME_24082026.DAT', '224_SALES_DATA_NNME_10082026.DAT', '150_SALES_DATA_NNME_24082026.DAT', '043_SALES_DATA_NNME_17082026.DAT', '222_SALES_DATA_NNME_17082026.DAT', '239_SALES_DATA_NNME_17082026.DAT', '050_SALES_DATA_NNME_10082026.DAT', '231_SALES_DATA_NNME_10082026.DAT', '252_SALES_DATA_NNME_24082026.DAT', '276_SALES_DATA_NNME_24082026.DAT', '102_SALES_DATA_NNME_10082026.DAT', '192_SALES_DATA_NNME_17082026.DAT', '300_SALES_DATA_NNME_24082026.DAT', '081_SALES_DATA_NNME_24082026.DAT', '074_SALES_DATA_NNME_10082026.DAT', '061_SALES_DATA_NNME_10082026.DAT', '187_SALES_DATA_NNME_17082026.DAT', '656_SALES_DATA_NNME_17082026.DAT', '002_SALES_DATA_NNME_24082026.DAT', '263_SALES_DATA_NNME_24082026.DAT', '117_SALES_DATA_NNME_10082026.DAT', '148_SALES_DATA_NNME_17082026.DAT', '251_SALES_DATA_NNME_17082026.DAT', '234_SALES_DATA_NNME_24082026.DAT', '259_SALES_DATA_NNME_10082026.DAT', '123_SALES_DATA_NNME_24082026.DAT', '257_SALES_DATA_NNME_10082026.DAT', 'app.py', '244_SALES_DATA_NNME_17082026.DAT', '529_SALES_DATA_NNME_17082026.DAT', '007_SALES_DATA_NNME_10082026.DAT', '260_SALES_DATA_NNME_17082026.DAT', '001_SALES_DATA_NNME_17082026.DAT', '266_SALES_DATA_NNME_10082026.DAT', '171_SALES_DATA_NNME_10082026.DAT', '268_SALES_DATA_NNME_10082026.DAT', '097_SALES_DATA_NNME_17082026.DAT', '303_SALES_DATA_NNME_17082026.DAT', '082_SALES_DATA_NNME_17082026.DAT', '109_SALES_DATA_NNME_24082026.DAT', '164_SALES_DATA_NNME_10082026.DAT', '210_SALES_DATA_NNME_24082026.DAT', '273_SALES_DATA_NNME_10082026.DAT', '275_SALES_DATA_NNME_17082026.DAT', '012_SALES_DATA_NNME_10082026.DAT', '084_SALES_DATA_NNME_10082026.DAT', '117_SALES_DATA_NNME_17082026.DAT', '004_SALES_DATA_NNME_24082026.DAT', '092_SALES_DATA_NNME_24082026.DAT', '061_SALES_DATA_NNME_17082026.DAT', '.ipynb_checkpoints', '187_SALES_DATA_NNME_10082026.DAT', '265_SALES_DATA_NNME_24082026.DAT', '656_SALES_DATA_NNME_10082026.DAT', '537_SALES_DATA_NNME_24082026.DAT', '270_SALES_DATA_NNME_24082026.DAT', '620_SALES_DATA_NNME_24082026.DAT', '192_SALES_DATA_NNME_10082026.DAT', '074_SALES_DATA_NNME_17082026.DAT', '087_SALES_DATA_NNME_24082026.DAT', '102_SALES_DATA_NNME_17082026.DAT', '231_SALES_DATA_NNME_17082026.DAT', '254_SALES_DATA_NNME_24082026.DAT', '239_SALES_DATA_NNME_10082026.DAT', '050_SALES_DATA_NNME_17082026.DAT', '143_SALES_DATA_NNME_24082026.DAT', '222_SALES_DATA_NNME_10082026.DAT', '158_SALES_DATA_NNME_24082026.DAT', '224_SALES_DATA_NNME_17082026.DAT', '043_SALES_DATA_NNME_10082026.DAT', '275_SALES_DATA_NNME_10082026.DAT', '101_SALES_DATA_NNME_24082026.DAT', '012_SALES_DATA_NNME_17082026.DAT', '199_SALES_DATA_NNME_24082026.DAT', '218_SALES_DATA_NNME_24082026.DAT', '084_SALES_DATA_NNME_17082026.DAT', '216_SALES_DATA_NNME_24082026.DAT', '303_SALES_DATA_NNME_10082026.DAT', '082_SALES_DATA_NNME_10082026.DAT', '164_SALES_DATA_NNME_17082026.DAT', '273_SALES_DATA_NNME_17082026.DAT', '001_SALES_DATA_NNME_10082026.DAT', '266_SALES_DATA_NNME_17082026.DAT', '171_SALES_DATA_NNME_17082026.DAT', '268_SALES_DATA_NNME_17082026.DAT', '097_SALES_DATA_NNME_10082026.DAT', '529_SALES_DATA_NNME_10082026.DAT', '007_SALES_DATA_NNME_17082026.DAT', '260_SALES_DATA_NNME_10082026.DAT', '560_SALES_DATA_NNME_24082026.DAT', '244_SALES_DATA_NNME_10082026.DAT', '259_SALES_DATA_NNME_17082026.DAT', '257_SALES_DATA_NNME_17082026.DAT', '148_SALES_DATA_NNME_10082026.DAT', '251_SALES_DATA_NNME_10082026.DAT', '575_SALES_DATA_NNME_24082026.DAT', '232_SALES_DATA_NNME_24082026.DAT', '092_SALES_DATA_NNME_17082026.DAT', '263_SALES_DATA_NNME_10082026.DAT', '117_SALES_DATA_NNME_24082026.DAT', '004_SALES_DATA_NNME_17082026.DAT', '265_SALES_DATA_NNME_17082026.DAT', '002_SALES_DATA_NNME_10082026.DAT', '061_SALES_DATA_NNME_24082026.DAT', '620_SALES_DATA_NNME_17082026.DAT', '081_SALES_DATA_NNME_10082026.DAT', '074_SALES_DATA_NNME_24082026.DAT', '537_SALES_DATA_NNME_17082026.DAT', '276_SALES_DATA_NNME_10082026.DAT', '102_SALES_DATA_NNME_24082026.DAT', '087_SALES_DATA_NNME_17082026.DAT', '252_SALES_DATA_NNME_10082026.DAT', '231_SALES_DATA_NNME_24082026.DAT', '050_SALES_DATA_NNME_24082026.DAT', '143_SALES_DATA_NNME_17082026.DAT', '158_SALES_DATA_NNME_17082026.DAT', '224_SALES_DATA_NNME_24082026.DAT', '150_SALES_DATA_NNME_10082026.DAT', '247_SALES_DATA_NNME_10082026.DAT', '084_SALES_DATA_NNME_24082026.DAT', '216_SALES_DATA_NNME_17082026.DAT', '101_SALES_DATA_NNME_17082026.DAT', '012_SALES_DATA_NNME_24082026.DAT', '218_SALES_DATA_NNME_17082026.DAT', '273_SALES_DATA_NNME_24082026.DAT', '109_SALES_DATA_NNME_10082026.DAT', '164_SALES_DATA_NNME_24082026.DAT', '210_SALES_DATA_NNME_10082026.DAT', '171_SALES_DATA_NNME_24082026.DAT', '268_SALES_DATA_NNME_24082026.DAT', '266_SALES_DATA_NNME_24082026.DAT', '007_SALES_DATA_NNME_24082026.DAT', '560_SALES_DATA_NNME_17082026.DAT', '257_SALES_DATA_NNME_24082026.DAT', '234_SALES_DATA_NNME_10082026.DAT', '259_SALES_DATA_NNME_24082026.DAT', '575_SALES_DATA_NNME_17082026.DAT', '232_SALES_DATA_NNME_17082026.DAT']